In [2]:
import numpy as np

In [26]:
X_array = np.array([[1,5,6], [4,6,7], [8,9,6]])
X_matrix = np.matrix([[1,5,6], [4,6,7], [8,9,6]])

In [28]:
'''
Przy tego typu operacji na obiekcie typu array wykonujemy podnoszenie do -1 potegi dla kazdego z elementow
co nie jest poprawne.
Na obiekcie typu matrix odwracanie macierzy nastepuje poprawnie
'''
X_array**-1.0 == X_matrix**-1

matrix([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [23]:
#Do poprawnego obrocenia macierzy typu array wykorzystujemy:
np.linalg.inv(X_array) == X_matrix**-1

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [24]:
#Dla obrocenia macierzy o typie matrix mozemy zastosowac takze I:
np.linalg.inv(X_array) == X_matrix.I

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])